### ISSUE TITLE
Updating tutorials according the new API

### ISSUE THREAD

**Issue by fverdugo** [gridap/Tutorials#54]
If your are willing to help, write down your name next the tutorials you want to update.

- [x] Tutorial 1: Poisson equation @fverdugo 
- [x] Tutorial 2: Code validation @fverdugo 
- [x] Tutorial 3: Linear elasticity @fverdugo
- [x] Tutorial 4: p-Laplacian @fverdugo
- [x] Tutorial 5: Hyper-elasticity @fverdugo
- [x] Tutorial 6: Poisson equation (with DG) @andre-massing
- [x] Tutorial 7: Darcy equation (with RT) @jesusbonilla 
- [x] Tutorial 8: Incompressible Navier-Stokes @oriolcg 
- [x] Tutorial 9: Stokes equation @oriolcg 
- [x] Tutorial 10: Isotropic damage model @fverdugo
- [x] Tutorial 11: Fluid-Structure Interaction @oriolcg

**Comment by fverdugo** [comment]
We are going to collect the changes in branch `new_api` https://github.com/gridap/Tutorials/tree/new_api
Once you have updated one tutorial, please push the changes to these branch.

Once all the work is done, we will merge this branch into master.

**Comment by fverdugo** [comment]
new new API is in `Gridap#kernel_refactoring` and will be soon in `Gridap#master`

**Comment by oriolcg** [comment]
Hi @fverdugo, I'm updating the FSI tutorial and I'm getting an error with the `apply` function in the following line: https://github.com/gridap/Tutorials/blob/ee4e354f311d6423916127d4b94f5242404d07eb/src/fsi_tutorial.jl#L322

I see that it's not in `Gridap.Arrays` anymore, but I cannot figure out how to resolve it. This particular line would be equivalent to the old `cell_measure` function, but this is not implemented yet on the new version, right?

**Comment by fverdugo** [comment]
Hi @oriolcg 

`apply` is now `lazy_map`. 

`cell_measure` is re-implemented as `get_cell_measure(trian)` in https://github.com/gridap/Gridap.jl/commit/f8a6de1de502e3bc0b5eece84a4b41cf52c073e5

(perhaps I change the name of this function since the returned vector has length == num cells in the background triangulation, instead of cells in the given triangulation)

**Comment by oriolcg** [comment]
>cell_measure is re-implemented as get_cell_measure(trian) in gridap/Gridap.jl@f8a6de1

Ok, then if I want the measure of an interface cell (facet), would it work if I do (or similar)?
```julia
h_bg = get_cell_measure(interface_trian)
h_i = lazy_map(Reindex(h_bg),interface_trian.cell_to_parent_cell)
```

By the way, commit gridap/Gridap.jl@f8a6de1 has not been merged to the branch `kernel_refactoring` yet, right?

**Comment by fverdugo** [comment]
> Ok, then if I want the measure of an interface cell (facet), would it work if I do (or similar)?

If you want the surface of each face in a boundary triangulation `S` with Lebesgue measure `dS`, then you can simply do:
```julia
∫(1)*dS
```

Note that this is not equivalent to this in general:
```julia
h_bg = get_cell_measure(S)
h_i = lazy_map(Reindex(h_bg),get_cell_id(S))
```

**Comment by oriolcg** [comment]
Thanks for the inputs @fverdugo . Now I'm facing another problem: it fails when evaluating an interface term like
```julia
∫( α*(vf.⁺-vs.⁻)⋅(uf.⁺-us.⁻) )*dΓ
```
The error message that I get is the following:
```
ERROR: MethodError: no method matching -(::Gridap.Geometry.SkeletonPair{Gridap.CellData.OperationCellField{ReferenceDomain},Gridap.CellData.OperationCellField{ReferenceDomain}}, ::Gridap.Geometry.SkeletonPair{Gridap.CellData.OperationCellField{ReferenceDomain},Gridap.CellData.OperationCellField{ReferenceDomain}})
```
I noticed that the `operate` function has been commented in src/Helpers/GridapTypes.jl. Can this be the cause of the problem?

I also get an error when defining multifield FE spaces from restricted triangulations. That is, using `model_fluid`/`model_solid` instead of `model` in the definition of the fluid/solid test FE space. This was not happening before (see original fsi_tutorial). Any clue about this issue?

**Comment by fverdugo** [comment]
Hi @oriolcg,

can you provide some more context?

**Comment by oriolcg** [comment]
In the current version of the [fsi_tutorial](https://github.com/gridap/Tutorials/blob/master/src/fsi_tutorial.jl) the FE spaces are defined as follows:
```julia
Vf = TestFESpace(
    model=model_fluid,
    valuetype=VectorValue{2,Float64},
    reffe=:Lagrangian,
    order=k,
    conformity =:H1,
    dirichlet_tags=["inlet", "noSlip", "cylinder"])

Vs = TestFESpace(
    model=model_solid,
    valuetype=VectorValue{2,Float64},
    reffe=:Lagrangian,
    order=k,
    conformity =:H1,
    dirichlet_tags=["fixed"])

Qf = TestFESpace(
  model=model_fluid,
  valuetype=Float64,
  order=k-1,
  reffe=:Lagrangian,
  conformity=:C0)
```

**Issue 1**
Using the restricted models (`model_fluid` and `model_solid`) for the definition of the FE spaces `Vf` and `Vs` in the refactored Gridap version results in an error in the check https://github.com/gridap/Gridap.jl/blob/e95c7251da09c866ead21af8c685f1804fae8d3f/src/Arrays/LazyArrays.jl#L234
If instead I use the full model `model` in the definition of the FE spaces `Vf` and `Vs`, the problem does not appear. 

**Issue 2**
When enforcing the interface condition using Nitsche's approach, I need to compute the integral of  jump of test functions against jump of unknowns. In the previous version, it was implemented as follows:
```julia
function a_fs(x,y)
  us_Γ, uf_Γ, p_Γ = x
  vs_Γ, vf_Γ, q_Γ = y
  us, uf, p = us_Γ.⁻, uf_Γ.⁺, p_Γ.⁺
  vs, vf, q = vs_Γ.⁻, vf_Γ.⁺, q_Γ.⁺
  α*(vf-vs)⋅(uf-us) + (vf-vs)⋅(p*n_Γfs-n_Γfs⋅σ_dev_f(ε(uf))) + (q*n_Γfs-χ*n_Γfs⋅σ_dev_f(ε(vf)))⋅(uf-us)
end
```
And in the new version I implemented it with the following expression:
```julia
a_fs((us,uf,p),(vs,vf,q)) = ∫( α*(vf.⁺-vs.⁻)⋅(uf.⁺-us.⁻) + (vf.⁺-vs.⁻)⋅(p.⁺*n_Γfs - n_Γfs⋅(σ_dev_f∘ε(uf.⁺))) + (q.⁺*n_Γfs-χ*n_Γfs⋅(σ_dev_f∘ε(vf.⁺)))⋅(uf.⁺-us.⁻) )*dΓ_fs
```
This last implementation gives an error when evaluating the term `(vf.⁺-vs.⁻)`. This error is related to the operator `-` for skeleton fields (or at least this is my interpretation of the error posted in the previous comment).

**Comment by fverdugo** [comment]
@oriolcg 

the normal vector `n_Γfs` is now a skeleton pair. You need to explicitly select which if the two possible normals you want, either `n_Γfs.⁺` or `n_Γfs.⁻`.  This provides more flexibility than before. Note that + is outwards to the fluid domain I guess.

The shorthand notation `jump(n·gradient(u))` for `n.⁺·gradient(u.⁺) + n.⁻·gradient(u.⁻)` also works, but you cannot use it in your case.

About the generation of FESpaces. Can you provide a MWE? This is tested in Gridap. It should work.

**Comment by oriolcg** [comment]
Thanks for the remark on the normal, I wasn't aware of that. However, I don't think this is the problem I'm having because I see the same behaviour in a simplified term that doesn't involve normal components:
```julia
∫( α*(vf.⁺-vs.⁻)⋅(uf.⁺-us.⁻) )*dΓ
```

Regarding the FE spaces issue, I see that there is the test `SurfaceCouplingTests.jl` in Gridap. In fact, I checked this test to try to understand what was the error. However, in this test there is only one FE space for solid and fluid velocities `V`, which is defined with the global model `model`, see https://github.com/gridap/Gridap.jl/blob/38b840dfc6e9ac4a0cd9a774465103941a4a1d87/test/GridapTests/SurfaceCouplingTests.jl#L76
In this test it is assumed that the velocity field is continuous on the interface (strong continuity), so you can use the same FE space for both domains. In the fsi_tutorial the continuity is weakly enforced, so there is the need to define two different FE spaces that, originally, were defined on each restricted discrete models.

What is done in the `SurfaceCouplingTests.jl` test, i.e. defining a global FE space and integration only on the restricted triangulations, also works for the fsi_tutorial. What doesn't work is defining the FE spaces using the restricted models. I'll create a MWE for this issue this evening.

**Comment by fverdugo** [comment]
@oriolcg can you push your code, so that I can take a look?

**Comment by fverdugo** [comment]
@oriolcg I have already found a bug:  https://github.com/gridap/Gridap.jl/pull/478

**Comment by oriolcg** [comment]
Great! Thanks @fverdugo! This solves the issue related to the different discrete models on the FE spaces, but I still have the problem with the `-` operator with skeleton fields. Any thought on what could be happening there?

**Comment by fverdugo** [comment]
Tutorials have been successfully run with Gridap#master in https://github.com/gridap/Tutorials/actions/runs/415136455 (except docs)

closing issue.
